name: Update Theme Screenshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-screenshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Set up WordPress with Docker
      run: |
        cat > docker-compose.yml << 'EOF'
        version: '3.8'
        services:
          wordpress:
            image: wordpress:latest
            ports:
              - "8000:80"
            environment:
              WORDPRESS_DB_HOST: db
              WORDPRESS_DB_USER: wordpress
              WORDPRESS_DB_PASSWORD: wordpress
              WORDPRESS_DB_NAME: wordpress
            volumes:
              - ./:/var/www/html/wp-content/themes/felixbarros
            depends_on:
              - db
              
          db:
            image: mysql:8.0
            environment:
              MYSQL_DATABASE: wordpress
              MYSQL_USER: wordpress
              MYSQL_PASSWORD: wordpress
              MYSQL_ROOT_PASSWORD: rootpassword
            volumes:
              - db_data:/var/lib/mysql
              
        volumes:
          db_data:
        EOF
        
    - name: Start WordPress
      run: |
        docker-compose up -d
        echo "Esperando que WordPress esté disponible..."
        
    - name: Wait for WordPress
      run: |
        timeout 120 bash -c 'until curl -f http://localhost:8000/ > /dev/null 2>&1; do
          echo "Esperando WordPress..."
          sleep 5
        done'
        echo "WordPress está disponible"
        
    - name: Install Playwright browsers
      run: npx playwright install chromium
      
    - name: Capture screenshot
      run: npm run screenshot
      
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet screenshot.png; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit screenshot
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add screenshot.png
        git commit -m "chore: update theme screenshot

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push
        
    - name: Clean up
      if: always()
      run: docker-compose down -v